### ISSUE TITLE
The Training does not start

### ISSUE THREAD

**Issue by savanigokhale** [thanosvlo/MARL-for-Anatomical-Landmark-Detection#6]
When I run DQN.py, a few errors were thrown. After I fixed those errors the script fetched the data correctly but the training does not start.

**Command:** python DQN.py --task train  --gpu 0 --files './data/filenames/image_files.txt' './data/filenames/landmark_files.txt'

**On terminal:**

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

[0205 09:33:32 @logger.py:90] Argv: DQN.py --task train --gpu 0 --files ./data/filenames/image_files.txt ./data/filenames/landmark_files.txt 

Not sure where I made the mistake. 
I am using the same versions of the packages required.

**Comment by thanosvlo** [comment]
The terminal output you posted just is a deprecation notice, make sure you are using TF 1.14 or earlier , the code has not been changed to work with TF 2.0, was there anything else in the console output to indicate the error ?

**Comment by savanigokhale** [comment]
I am using TF 1.14.0.
There's nothing in the console output which indicates error.

I printed a few statements to check on what step it is freezing. 

**Console output:**
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

in class model
in class medical player

Landmark files  ['./data/landmarks/ADNI_002_S_0816_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070217005829488_S18402_I40731.txt', './data/landmarks/ADNI_003_S_1059_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070501173720913_S22300_I52816.txt', './data/landmarks/ADNI_005_S_0448_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20061212165540546_S14032_I32875.txt', './data/landmarks/ADNI_006_S_0681_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20080224150248153_S18451_I92305.txt', './data/landmarks/ADNI_007_S_0293_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070118022549519_S12193_I36549.txt', './data/landmarks/ADNI_009_S_1354_MR_MPR__GradWarp__N3__Scaled_Br_20070717183309825_S27634_I60443.txt', './data/landmarks/ADNI_010_S_0786_MR_MPR____N3__Scaled_Br_20070807153633938_S19638_I65597.txt', './data/landmarks/ADNI_011_S_0010_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20061208114538147_S8800_I32270.txt', './data/landmarks/ADNI_133_S_0638_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070813172348807_S16608_I67531.txt', './data/landmarks/ADNI_941_S_1363_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070801202916120_S28008_I63897.txt']

length of image files  10

length of landmark files  10
in restart episode
in new random game

length of image files in num_files   10
[57, 57] [138, 117] [78, 52]

length of image files in num_files   10
num actions and files 6 10
[0205 15:17:09 @logger.py:90] Argv: DQN.py --task train --gpu 0 --files ./data/filenames/image_files.txt ./data/filenames/landmark_files.txt

in func get config
in get_player 
in class medical player

Landmark files  []

length of image files  0

length of landmark files  0
in restart episode
in new random game

length of image files in num_files   0
